version: "3.2"

networks:
  testnet:
    external:
      name: testnet

services:
  central_server:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ip-172-31-26-224
    image: presto412/storev1
    hostname: nyc.central.com
    command: npm start
    volumes:
      - "/tmp/uploads:/tmp/uploads"
      # - ".:/usr/src/app/"
    environment:
      - SELF_HOSTNAME=nyc.central.com
    ports:
      - "80:3000"
    networks:
      testnet:
        aliases:
          - nyc.central.com

  storage_toronto:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ip-172-31-4-134
    image: presto412/storev1
    hostname: toronto.storage.com
    command: npm start
    ports:
      - "80:3000"
    environment:
      - SELF_HOSTNAME=toronto.storage.com
    volumes:
      - "/tmp/uploads:/tmp/uploads"
      # - ".:/usr/src/app/"
    networks:
      testnet:
        aliases:
          - toronto.storage.com

  storage_singapore:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ip-172-31-18-88
    image: presto412/storev1
    hostname: singapore.storage.com
    command: npm start
    ports:
      - "80:3000"
    environment:
      - SELF_HOSTNAME=singapore.storage.com
    volumes:
      - "/tmp/uploads:/tmp/uploads"
      # - ".:/usr/src/app/"
    networks:
      testnet:
        aliases:
          - singapore.storage.com

  storage_amsterdam:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == amsterdam
    image: presto412/storev1
    hostname: amsterdam.storage.com
    command: npm start
    volumes:
      - "/tmp/uploads:/tmp/uploads"
      # - ".:/usr/src/app/"
    ports:
      - "80:3000"
    environment:
      - SELF_HOSTNAME=amsterdam.storage.com
    networks:
      testnet:
        aliases:
          - amsterdam.storage.com

  storage_bangalore:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ip-172-31-24-55
    image: presto412/storev1
    command: npm start
    hostname: bangalore.storage.com
    environment:
      - SELF_HOSTNAME=bangalore.storage.com
    ports:
      - "80:3000"
    volumes:
      - "/tmp/uploads:/tmp/uploads"
      # - ".:/usr/src/app/"
    networks:
      testnet:
        aliases:
          - bangalore.storage.com
